### PR TITLE
Add an extension method to convert ConfigReaderFailures into a NonEmptyList

### PR DESCRIPTION
**Pull request by ruippeixotog**

### CODE REVIEW

**Review by derekmorr — APPROVED** [review]

**Comment by derekmorr** [comment]
LGTM. I was toying with this is too, since ConfigReaderFailures is isomorphic to NonEmptyList.

**Review by melrief — CHANGES_REQUESTED** [review]
LGTM but you may want to add the change to the CHANGELOG

**Comment by ruippeixotog** [comment]
@melrief this was added to `pureconfig-cats` and not to the core, and our "policy" has been not to track changes in the modules in the CHANGELOG until now.

**Review by melrief — APPROVED** [review]
@ruippeixotog right but we had a discussion about adding the CHANGELOG for the modules. I'll approve this as it is but I think we should consider adding a CHANGELOG to the module pureconfig-cats with the changes for the next version.

**Comment by ruippeixotog** [comment]
I agree that we should have a change log for the modules, we just need to decide if we want a separate CHANGELOG file for each module or a single one for everything :)

**Pull request merged**
