### PR TITLE
Change use of CrossVersion.full to CrossVersion.patch.

### PR DESCRIPTION
**Pull request by sh0hei**
Ref. https://github.com/typelevel/scala/issues/135

### CODE REVIEW

**Review by melrief — CHANGES_REQUESTED** [review]
@sh0hei thanks for the PR, it looks fine and I have only one comment: can you please revert all the changes to the style of the project? I'd like to have a clean commit for this one in case there are issues.

**Comment by sh0hei** [comment]
@melrief Revert style format :)

**Review by melrief — APPROVED** [review]

**Comment by melrief** [comment]
Thanks @sh0hei ! I'd like to add you to the [CONTRIBUTORS](https://github.com/melrief/pureconfig/blob/master/CONTRIBUTORS) file, if you agree to have your name in the project, please make another PR in which you add one line to the CONTRIBUTORS file with your name, email address and username

**Comment by sh0hei** [comment]
@melrief Of course! Thank you very much! PR will be made now.

**Pull request merged**
