### PR TITLE
add jcazevedo and leifwickland to core pom file

### PR DESCRIPTION
**Pull request by melrief**

### CODE REVIEW

**Comment by melrief** [comment]
@jcazevedo @leifwickland a quick PR to add you to the pom.xml file generated for pureconfig for the next releases. Sorry to do this only now. When you can, have a look at your info and tell me if you want to change anything or if it's ok for you.

**Review by jcazevedo — APPROVED** [review]
LGTM

**Comment by leifwickland** [comment]
LGTM 👍

**Review by leifwickland — APPROVED** [review]
LGTM 👍

**Pull request merged**
