### PR TITLE
Add ConfigReader and ConfigWriter for Char

### PR DESCRIPTION
**Pull request by stefanobaghino**
There are no tests right now, I looked around but found no tests for primitive types. I guess I could use some guidance in this regard. 🙂

### CODE REVIEW

**Comment by ruippeixotog** [comment]
This looks good!

Tests for basic converters are in [BasicConvertersSuite.scala](https://github.com/pureconfig/pureconfig/blob/master/core/src/test/scala/pureconfig/BasicConvertersSuite.scala). Adding `checkArbitrary[Char]` there will use scalacheck to verify that all `Char` values convert to and from a config in a consistent way. For completeness, you should also add `checkFailure` tests for an empty string and a string with more than one character.

**Comment by stefanobaghino** [comment]
Ah-ah, cool, that's why IntelliJ couldn't find tests for me. Thanks, I've added the test. There seems to be something not working with Scala 2.12 on Travis CI but I can't tell what it its.

**Comment by stefanobaghino** [comment]
Wow, I'm finding out stuff about `String`s in Java that I didn't know, fix is coming.

**Comment by stefanobaghino** [comment]
Now it's ok. For some reason `ConfigWriter.forPrimitive[Char]` doesn't work.

**Comment by stefanobaghino** [comment]
I have no idea why it's failing in Scala 2.12, the jobs exits with an error code but all tests pass. 😐

**Comment by ruippeixotog** [comment]
> Now it's ok. For some reason ConfigWriter.forPrimitive[Char] doesn't work.

`forPrimitive` relies on `ConfigValueFactory.forAnyRef`, which [doesn't support Char](https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigImpl.java#L204). `toDefaultString` seems fine.

> I have no idea why it's failing in Scala 2.12, the jobs exits with an error code but all tests pass. 😐

According to Travis, `The command "if [[ $TRAVIS_SCALA_VERSION =~ ^2\.12.* ]]; then git diff --exit-code; fi" exited with 1.`. This happens because the code isn't formatted according to the rules defined for the project. If you run `sbt compile` on your computer you'll notice that the code gets reformatted automatically. You should commit those changes in order for the build to pass :)

**Comment by stefanobaghino** [comment]
I see, thanks.

**Comment by stefanobaghino** [comment]
Yay, thanks for the guidance!

**Review by ruippeixotog — APPROVED** [review]
LGTM. Thanks, @stefanobaghino!

**Comment by jcazevedo** [comment]
LGTM. Thanks for this, @stefanobaghino!

**Comment by jcazevedo** [comment]
Thanks for the PR @stefanobaghino! We would like to add you to the [CONTRIBUTORS](https://github.com/pureconfig/pureconfig/blob/master/CONTRIBUTORS) file. If you agree, please submit another PR in which you add a line with your name, your email (optional) and your username, in line with PRs such as #118, #152 or #160.

**Comment by stefanobaghino** [comment]
Thanks for helping me out with this modest contribution, it'll be my pleasure to add myself to the `CONTRIBUTORS` file. Cheers!

**Pull request merged**
