### PR TITLE
Enable coverage for Scala 3

### PR DESCRIPTION
**Pull request by ruippeixotog**
Coverage is supported since Scala 3.2, so we can enable it in PureConfig now.

### CODE REVIEW

**Comment by ruippeixotog** [comment]
I believe https://github.com/scoverage/sbt-scoverage/issues/444 might be the reason why this is failing.

**Comment by ruippeixotog** [comment]
sbt-scoverage works since Scala 3.2.2, so this is good to go now.

**Comment by ruippeixotog** [comment]
@jcazevedo @leifwickland would you mind taking a quick look at this? It should be easy to review.

**Review by leifwickland — APPROVED** [review]
Thanks, @ruippeixotog!

**Review by jcazevedo — APPROVED** [review]
Thanks!

**Pull request merged**
