### PR TITLE
fix myIntWriter typo

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Review by derekmorr — APPROVED** [review]
Thanks!

**Review by leifwickland — APPROVED** [review]
Thanks, @jcranky

**Comment by ruippeixotog** [comment]
The build is failing because of an error checking the SSL certificate of one of the webpage links, which is obviously not related with your change. I'll disable SSL peer verification on the build and test this again tonight :)

**Review by ruippeixotog — APPROVED** [review]

**Comment by jcranky** [comment]
thanks :)

**Pull request merged**
