### PR TITLE
Update PureConfig to Scala 3.0

### PR DESCRIPTION
**Pull request by ruippeixotog**
Scala 3.0 final is out!

### CODE REVIEW

**Comment by timothyklim** [comment]
`org.scalatestplus %% scalacheck-1-15` is available now

**Review by jcazevedo — APPROVED** [review]
Thanks for this! 🎉

**Comment by sergiuszkierat** [comment]
@jcazevedo, [scala3-migrate](https://github.com/scalacenter/scala3-migrate) raises an error, when can we expect artifacts for `3.0.0`?
```
sbt> migrate-libs root
[info] 
[info] 
[info] Starting to migrate libDependencies for root
[info] 
[info] X             : Cannot be updated to scala 3
[info] Valid         : Already a valid version for Scala 3
[info] To be updated : Need to be updated to the following version
[info] 
[info] com.github.pureconfig:pureconfig:0.15.0                  -> X : Contains Macros and is not yet published for 3.0.0
```

**Comment by jcazevedo** [comment]
@sergiuszkierat: We should be making a release for Scala 3.0.0 in the near future. Note that it might still take a while before we support generic derivation of `ConfigReader`s and `ConfigWriter`s for Scala 3. For now, only pureconfig-core should be available.

**Comment by sergiuszkierat** [comment]
Thanks for updating me. As far as I know, we should follow https://github.com/pureconfig/pureconfig/issues/970 :eye:

**Pull request merged**
