### PR TITLE
Add basic spec directory and include basic spec.

### PR DESCRIPTION
**Pull request by shelbyd**
#16

### CODE REVIEW

**Comment by Phlosioneer** [comment]
This is just duplicating the work I'm doing on the test/ directory. Can we work together instead?

**Comment by pureconfig** [comment]
What's the sensible way to avoid duplication here?

**Comment by shelbyd** [comment]
My idea, admittedly not communicated, was to have the `spec` directory be the, well, spec for the language. I was planning on migrating the existing tests in `tests/success` to the `spec` piecemeal after getting the basic foundation in place.

I wanted to do a smaller PR so that we could talk about the layout and general approach without being distracted by 100s of lines.

**Comment by pureconfig** [comment]
@shelbyd Makes sense to me

**Pull request merged**
