### PR TITLE
Update cats-effect, fs2

### PR DESCRIPTION
**Pull request by kubukoz**
Currently at
- cats-effect v1.0.0
- fs2 v1.0.0
- http4s v0.19.0-M3 (waiting for a release compatible with fs2 v1.0.0)

WIP because I doubt we want to merge incompatible/unstable dependencies 🗡 

(I'll update the tut tests around tomorrow)

### CODE REVIEW

**Comment by kubukoz** [comment]
Seeing that http4s 0.19 might not be out for some time, maybe it'll be a good idea to separate it into another PR... I'll ask around and see when we can expect a release.

**Comment by ruippeixotog** [comment]
Hi @kubukoz, we'll probably release a new version of PureConfig in the next days. Do you want to do the last steps to take this PR out of WIP? :)

**Comment by kubukoz** [comment]
Hi, i'm afraid one way or another we'll have binary compatibility issues or an unstable version of http4s. Http4s has been released at 0.19.0, but it was a release made mistakenly instead of 0.19.0-M4, and they'll most likely break compat by 0.19.1. if we release this without the http4s changes, the old version will be incompatible with the cats-effect and fs2 versions we update here :/

**Comment by ruippeixotog** [comment]
Let's leave http4s out of the update then. In my opinion, modules must be treated independently and if some module is ready to be updated while others aren't, we should update what we can regardless of whether the two modules work frequently together.

People using only cats-effect and/or fs2 will still benefit from the upgrade, as well as http4s users that don't rely on cats-effect and fs2 modules. http4s users using other modules can keep using PureConfig 0.9 until a stable http4s version is released. What do you think?

**Comment by kubukoz** [comment]
Sure, sounds like a plan. So the http4s module won't be released in this round?

**Comment by ruippeixotog** [comment]
We always release a new version for all modules at once, but the http4s module will still target the old version.

**Comment by kubukoz** [comment]
So it'll use incompatible dependencies, I imagine

**Comment by ruippeixotog** [comment]
I'm not sure if I'm understanding the issue, but if you mean that the next version of `pureconfig-http4s` won't be usable with the next version of `pureconfig-fs2` or `pureconfig-cats-effect`, that's right, those will be incompatible. We do not guarantee dependency compatibility between different PureConfig modules, we only guarantee compatibility of each module with the latest PureConfig version.

(Let's put things into perspective here: the http4s module has literally one reader, and a trivial one at that. I'm sure people won't find too much trouble to write their own `Uri` readers in the meantime 🙂)

**Comment by kubukoz** [comment]
Fair enough. I didn't look that much at the code in the module ;) I'll follow up with the changes soon!

**Comment by kubukoz** [comment]
@ruippeixotog I reverted the http4s change, rebased & squashed. Sorry for stalling. We should be ready to go with this now :)

**Comment by leifwickland** [comment]
@kubukoz It looks like the build is broken due to failures when running tut for fs2. See https://travis-ci.org/pureconfig/pureconfig/jobs/442571569#L1488.

**Comment by kubukoz** [comment]
I'm on it.

**Review by ruippeixotog — APPROVED** [review]

**Comment by ruippeixotog** [comment]
Thanks for doing this, @kubukoz! 🙂

**Comment by kubukoz** [comment]
It's a pleasure :D

**Pull request merged**
