### PR TITLE
add entry for coulomb integration

### PR DESCRIPTION
**Pull request by erikerlandson**
re-submission of #558 to cleanly rebase off latest master

### CODE REVIEW

**Comment by erikerlandson** [comment]
(┛ಠ_ಠ)┛彡┻━┻

**Comment by jcazevedo** [comment]
After digging through Travis CI's documentation, it seems that secret environment variables [are not exposed](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) in PRs sent from forks. That explains why we're getting an unauthorized response when trying to post a comment on the `diff_website` CI job in this PR and why PRs coming from branches in this repository (see #563) have no issues.

Unfortunately, I don't think we can have this CI job posting comments to GitHub without an external service that would hide the API key.

**Review by ruippeixotog — APPROVED** [review]

**Comment by ruippeixotog** [comment]
Oh, makes sense. Let's merge this PR and figure out a better solution for this later.

@erikerlandson thanks for building the integration and for adding this entry here!

**Comment by erikerlandson** [comment]
@ruippeixotog @jcazevedo thank you! That is an evil little integration bug :frowning:

**Pull request merged**
