### PR TITLE
378 - Added reader and writer for generic map

### PR DESCRIPTION
**Pull request by anshulbajpai**

### CODE REVIEW

**Review by ruippeixotog — APPROVED** [review]
LGTM! As @melrief said on Gitter, as we increase the number of configurable converters we should start organizing them in subpackages for better discoverability. Right now I think this is still ok, though.

**Review by melrief — APPROVED** [review]
LGTM, good code!

**Comment by melrief** [comment]
@anshulbajpai before we merge, can I ask you to add a section to [CHANGELOG.md](https://github.com/pureconfig/pureconfig/blob/master/CHANGELOG.md) for release 0.9.2 in which you describe the new feature? You can see an example of unreleased version [here](https://github.com/pureconfig/pureconfig/commit/4526830c0d5e46f264488487bcee3f52ef366c24#diff-4ac32a78649ca5bdd8e0ba38b7006a1eL1).

**Comment by melrief** [comment]
@anshulbajpai thank you for your contribution! We would like to add you to the [CONTRIBUTORS](https://github.com/pureconfig/pureconfig/blob/master/CONTRIBUTORS) file. If you agree, please submit another PR in which you add a line with your name, your email (optional) and your username, in line with PRs such as #118, #152 or #160.

**Comment by anshulbajpai** [comment]
@melrief - will do, thanks!

**Pull request merged**
