### PR TITLE
Support Scala 3 in cats module

### PR DESCRIPTION
**Pull request by limansky**
I've solved issues with building `cats` module for Scala 3. The only thing I'm not sure if `publishMavenStyle` should be kept set false.

### CODE REVIEW

**Comment by limansky** [comment]
I've added Scala 3 to fs2, http4s, ip4s and sttp as well. All of these modules are published using scala 3.1, so I added Scala 3.1 as a compiler. To make them publishing, I created a setting minScala3Version and set `publish / skip` according to its value.

**Comment by limansky** [comment]
JFYI https://github.com/Comcast/ip4s/issues/341

**Comment by limansky** [comment]
I have no idea why sbt tries to build modules supporting Scala 3.1 only with Scala 3.0. It works fine when runnig `+compile` or `+test`, but fails if the version is specified via `++`. I'm trying to figure out what's going on, but it looks like I've stuck with it.

**Comment by pslaski** [comment]
What is the status of this PR? Are you planning publishing pureconfig modules for scala 3?

**Comment by ruippeixotog** [comment]
@limansky I believe this PR is failing because of https://github.com/sbt/sbt/issues/6915 - SRT isn't dealing correctly with Scala 3 in cross-compilation and projects that only support Scala 3.1 are being complied with Scala 3.0.x too.

**Comment by limansky** [comment]
@ruippeixotog yep, it seems like the root cause is the issue in sbt. If it acceptable for pureconfig team, we can just use Scala 3.1 for all Scala 3 modules.

**Comment by ruippeixotog** [comment]
No, that's not ok since it will force every library that depends on PureConfig to upgrade to Scala 3.1 as well (even if they are not using any of the affected modules). I'd say we can wait for SBT to be fixed and released before we merge this.

**Comment by ruippeixotog** [comment]
Superseded by #1352.

**Pull request closed without merging**
