### PR TITLE
Resolve issue #135

### PR DESCRIPTION
**Pull request by stsatlantis**
Resolves issue #135

### CODE REVIEW

**Review by melrief — APPROVED** [review]
Thanks for the contribution! I'd like @jcazevedo to have a look at this too because he is the main implementor of the `syntax` package but then we can merge it.

**Review by jcazevedo — CHANGES_REQUESTED** [review]
Can you also add a test for the positive case, i.e. when `toOrThrow` succeeds and doesn't throw an exception?

**Comment by stsatlantis** [comment]
Extra test added let me know if you want more complex tests

**Comment by jcazevedo** [comment]
Thanks for this, @stsatlantis! There's no need for more complex tests.

We would like to add you to the [CONTRIBUTORS](https://github.com/melrief/pureconfig/blob/master/CONTRIBUTORS) of the library. If you agree, please make another PR that just adds one line to the file with your name, the email and your username.

**Review by jcazevedo — APPROVED** [review]

**Comment by melrief** [comment]
Nice!

**Pull request merged**
