### PR TITLE
#31 Introduce property-based testing

### PR DESCRIPTION
**Pull request by p16i**
ref #31

### CODE REVIEW

**Comment by melrief** [comment]
Thanks @heytitle for the PR. If you agree, I would like to add you to the [CONTRIBUTORS](https://github.com/melrief/pureconfig/blob/master/CONTRIBUTORS) file.

**Comment by p16i** [comment]
@melrief yep, I totally agree. 

btw, should we also implement this for another tests as well?

**Comment by melrief** [comment]
Yes, for all the data structures I would like to have a test based on a random instance. This PR is a good start.

**Comment by p16i** [comment]
ok, then I'll try to make a another PR.

**Comment by melrief** [comment]
In the meanwhile, welcome among the [CONTRIBUTORS](https://github.com/melrief/pureconfig/blob/1eed35f7d109abc24feeb91c3cb8e5370ccb94c5/CONTRIBUTORS#L7) and thanks for this PR!

**Comment by leifwickland** [comment]
Welcome, @heytitle!

**Pull request merged**
