### PR TITLE
Changelog 0.6.0

### PR DESCRIPTION
**Pull request by melrief**

### CODE REVIEW

**Review by ruippeixotog — CHANGES_REQUESTED** [review]
The changelog is still missing the new converter for `java.net.URI` (#129) and the change from `Try` to `Either` in `CoproductHint` (#134). Other than that, LGTM!

**Comment by melrief** [comment]
@ruippeixotog added both, thanks. I have one question about best practices with the changelog: do we have to link the issue involved? We are not doing it right now but it could be useful for the user to track what the point means.

**Comment by ruippeixotog** [comment]
Yeah, we're not enforcing it now but it could be a good idea to reference either the pull request (always present) or the issue (not always present, but possibly more informative) relative to each change.

**Review by ruippeixotog — APPROVED** [review]

**Comment by melrief** [comment]
I won't merge this yet because we need the last change from @jcazevedo with #85 and the release date.

**Review by leifwickland — APPROVED** [review]
Thanks, @melrief!

**Pull request merged**
